### ISSUE TITLE
Running on macOS  (could not find required version for pyqt5-qt5)

### ISSUE THREAD

**Issue by AR-AK** [osinenkop/regelum-control#2]
I was trying to install `regelum` on `macOS Sonoma 14.1.2` with `Python 3.11.6` (other versions where also checked), the following error appeared:

<img width="1438" alt="SCR-20240327-msmq" src="https://github.com/osinenkop/regelum-control/assets/152798933/ea3b5519-babe-41ac-8009-fe3a85f8a78a">

Doing the following helped me to make it work on macOS (with M1/M2) processors:

1. Create an empty workspace folder
2.  Clone the repo `git clone https://github.com/osinenkop/regelum-control.git `
3. In your workspace folder, Open the file `pyproject.toml` and change the version of `pyqt5-qt5` so that the corresponding line becomes `pyqt5-qt5 = "=5.15.13"`
4. Create a `venv` python virtual environment
5. Activate the `venv` and do the following in the current running terminal
```
pip install cython
brew install hdf5
brew install c-blosc
export HDF5_DIR=/opt/homebrew/opt/hdf5 
export BLOSC_DIR=/opt/homebrew/opt/c-blosc
pip install tables
pip install -e .
```
Now you have `regelum-control` installed and ready to run!

**Comment by bolychevanton** [comment]
Thank you!

Fixed pyqt dependency issue in  [v0.3.2](https://github.com/osinenkop/regelum-control/releases/tag/v0.3.2)



However, I will not close the issue for a while, because I want to find a little bit more elegant way to solve the issue with hdf5
